# Generated by Django 2.2.28 on 2022-12-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0003_auto_20221207_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Email',
            new_name='username',
        ),
    ]
