# Generated by Django 2.2.28 on 2022-12-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0005_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
