# Generated by Django 2.2.28 on 2022-12-09 07:18

from django.db import migrations, models
from django.conf import settings



class Migration(migrations.Migration):

    dependencies = [
         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicalapp', '0007_medicine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expdate',
            field=models.DateField(max_length=7, null=True),
        ),
    ]
