# Generated by Django 2.2.28 on 2022-12-10 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0008_medicine_expdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expdate',
            field=models.DateField(max_length=7, null=True, verbose_name=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
